### ISSUE TITLE
React attempted to reuse markup in a container but the checksum was invalid.

### ISSUE THREAD

**Issue by gialdeyn** [yury-dymov/habr-app#1]
Вот этот контент (`/src/server.js:74`) надо обернуть в ещё один пустой див:
`<div id="react-view">${componentHTML}</div>`
Вот так:
`<div id="react-view"><div>${componentHTML}</div></div>`

Иначе при перезагрузке `F5` страницы, требующей авторизации (например, страницы `/time`), будет ошибка:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div data-reactroot="
```

В [третьей части туториала на хабре](https://habrahabr.ru/post/310952/) в данной ошибке обвинялась добавленная панелька девтулзов:
> виновником является redux-dev-tools

Возможно, это всё-таки был недостающий див. У меня с ним эта ошибка больше не проявляется.

<details>
  <summary>[Spoiler-oбъяснение на английском]</summary>
  Why does this work? On the client, React has a propensity to wrap its rendering of your root component with a superfluous div. ReactDOMServer.render doesn't seem to behave in this manner, thus when one renders into the same container isomorphically, the Adler-32 checksum of your DOM differs.

Взято <a target='_blank' href='http://stackoverflow.com/questions/33521047/warning-react-attempted-to-reuse-markup-in-a-container-but-the-checksum-was-inv'>отсюда</a>.
</details>
&nbsp;

_PS: Спасибо за туториал - он прекрасен._

**Comment by yury-dymov** [comment]
@gialdeyn, о, прикольно. Я думал, что redux-dev-tools ломает SSR и не особенно пытался разобраться. Попробую обернуть в div и посмотреть, что получится. Если поможет — обновлю еще пачку своих проектов :)

**Comment by yury-dymov** [comment]
Да, действительно помогло. 

Closed via https://github.com/yury-dymov/habr-app/commit/100fa96c7e0ea1730a5a3f3aba147706fb63b07a & https://github.com/yury-dymov/habr-app/commit/724b2ac0dd8cb6f34eb2c66ade9348ac41d1c5d7

**Comment by yury-dymov** [comment]
@gialdeyn, update. Интуиция мне подсказала, что как-то слишком просто получилось и все это странно. Почитал я тему из SSO и понял, что был интуиция была права — твой вариант убирает ошибку, но ломает SSR наглухо.

Вот вариант получше (был предложен хабравчанином Lerayne)

в src/server.js
```JavaScript
<div id="react-view">${componentHTML}</div>
<div id="dev-tools"></div>
```

в src/client.js 
```JavaScript
ReactDOM.render(component, document.getElementById('react-view'));
ReactDOM.render(<DevTools store={store} />, document.getElementById('dev-tools'));
```

При этом я сделал client.dev.js и client.prod.js соответственно

**Comment by daryn-k** [comment]
Спасибо автору issue за решение.

Но я бы всем советовал снести этот devtools, который мешается на странице, и пользоваться redux-devtools-extension. Для этого в client.dev.js надо поменять:
```
import { applyMiddleware, createStore, compose } from 'redux';
import thunk from 'redux-thunk';
import { composeWithDevTools } from 'redux-devtools-extension';
import rootReducer from './reducers';

const composeEnhancers = composeWithDevTools({});

export default function (initialState = {}) {
  const store = createStore(rootReducer, initialState, compose(
      applyMiddleware(thunk),
      composeEnhancers(
          applyMiddleware(thunk)
      )
    )
  );

  if (module.hot) {
    module.hot.accept('./reducers', () =>
      store.replaceReducer(require('./reducers').default)
    );
  }

  return store;
}
```
Просто надо установить сам redux-devtools-extension через npm install --save-dev redux-devtools-extension и [плагин](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=ru) для браузера.

Плюс в src/server.js я бы поменял функцию render HTML на

```
function renderHTML(componentHTML, initialState) {
  return `<!DOCTYPE html>` +
      `<html>` +
      `<head>` +
      `<meta charset="utf-8">`+
      `<meta name="viewport" content="width=device-width, initial-scale=1.0">` +
      `<title>Hello React</title>` +
      `<link rel="stylesheet" href="${assetUrl}/public/assets/styles.css">` +
      `<script type="application/javascript">` +
      `window.REDUX_INITIAL_STATE = ${JSON.stringify(initialState)};` +
      `</script>` +
      `</head>` +
      `<body>` +
      `<div id="react-view"><div>${componentHTML}</div></div>` +
      `<script type="application/javascript" src="${assetUrl}/public/assets/bundle.js"></script>` +
      `</body>` +
      `</html>`;
}
```
Это уберёт лишние пробелы, итоговый HTML будет в одну сплошную строчку.

**Comment by yury-dymov** [comment]
> Плюс в src/server.js я бы поменял функцию render HTML на

это плохое решение, которое убивает весь смысл использования шаблонов, пробелы можно убрать иначе, правда в данном случае смысла в этом предельно немного
