### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mymtwcom** [yury-dymov/habr-app#2]
Вы не могли бы объяснить а как после этой строки в `webpack.config.js`:
`let cssName            = process.env.NODE_ENV === 'production' ? 'styles-[hash].css' : 'styles.css';`
css будет подключаться в production приложение, а именно когда оно отрендерено сервером.
Ну т.е. если я правильно понял суть, для запуска приложения в production с server-side rendering пишем: 
1. `npm run build`
2. дальше nginx у отдаем такую строку `express server.js`
3. но мы же получили после npm run build: хэши `styles-[hash].css` и `bundle-[hash].js`. А в шаблоне в server.js написано другое `<link rel="stylesheet" href="${assetUrl}/public/assets/styles.css">`
Как можно подключить сгенеренные хэши `styles-[hash].css` именно для продакшена? 

Спасибо.

**Comment by yury-dymov** [comment]
@mymtwcom, привет. Я делаю это примерно так:

#### src/server.js
```JavaScript
...
function getAssets() {
  let bundle = 'bundle.js';
  let styles = 'styles.css';

  if (process.env.NODE_ENV === 'production') {
    const assetPath = path.join(__dirname, '../public/static/assets');
    const files = fs.readdirSync(assetPath);

    files.forEach((file) => {
      if (file.match('^bundle')) {
        bundle = file;
      } else if (file.match('^styles')) {
        styles = file;
      }
    });
  }

  return { bundle, styles };
}

const { bundle, styles } = getAssets();

...

function renderHTML({ componentHTML }) {
  return `
    <!DOCTYPE html>
      <html>
      <head>
           ...
           <link rel="stylesheet" href="${assetUrl}/public/assets/${styles}">
      </head>
      <body>
        <div id="react-view">${componentHTML}</div>
        <script type="application/javascript" src="${assetUrl}/assets/${bundle}"></script>
      </body>
    </html>
  `;
}

```

Вероятно можно сделать лучше, но я делаю так в нескольких проектах в продакшене и меня устраивает

**Comment by mymtwcom** [comment]
огромное спасибо!
