### ISSUE TITLE
Раскладка на прод

### ISSUE THREAD

**Issue by densuk** [yury-dymov/habr-app#3]
Добрый день. Познакомился с понятием современных изоморфных приложений по вашему докладу на хабре, за что Вам спасибо.

Но до сих пор не совсем понимаю как это должно жить на проде.

Судя по всему, дополнительно должен собираться серверный код, дабы нода видела его как модуль.

И чтобы в последствии работала команда ```node server.js```

**Comment by yury-dymov** [comment]
Посмотрите в сторону pm2
