### ISSUE TITLE
"npm run nodemon" не работает

### ISSUE THREAD

**Issue by daryn-k** [yury-dymov/habr-app#5]
Команда "npm run nodemon" не работает (из readme)

**Comment by yury-dymov** [comment]
```Bash
git clone https://github.com/yury-dymov/habr-app.git
npm i
npm run nodemon
```

![image](https://user-images.githubusercontent.com/1292558/27456657-c12a58ca-5756-11e7-9f0c-6e4723e42478.png)

So it works

**Comment by daryn-k** [comment]
Эта ошибка возникает на Windows

На Linux сервер запускается, но не видит css и bundle.js, а потом возникает кучу ошибок

40:56  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

Сайт без css, redux-dev-tools не открывается

**Comment by daryn-k** [comment]
В принципе, меня интересует только redux-dev-tools. Без PREDLOADED_STATE на server-rendering он работает нормально. Но а так не работает. Замучился. Второй месяц сижу и не могу элементарно сделать то, как мне надо. То одно, то другое валится. Нервы на пределе!

**Comment by yury-dymov** [comment]
> 40:56 error Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style
отключи линтер - это некритичные ошибки и на работоспособность никак не влияет

> На Linux сервер запускается, но не видит css и bundle.js, а потом возникает кучу ошибок
> Замучился. Второй месяц сижу и не могу элементарно сделать то, как мне надо. 
Дочитай один раз README и сделай, как там написано, и все у тебя получится

![image](https://user-images.githubusercontent.com/1292558/27459576-d651bb8c-5763-11e7-8fc9-0d8f726096a1.png)
![image](https://user-images.githubusercontent.com/1292558/27459583-f4eb53be-5763-11e7-8b3f-4ab092bc3921.png)
![image](https://user-images.githubusercontent.com/1292558/27459594-ffd4a384-5763-11e7-8700-c01e0d532fff.png)

**Comment by daryn-k** [comment]
Всё равно не работает
