### ISSUE TITLE
Неправильно указан путь к js и css файлам для продакшн сборки

### ISSUE THREAD

**Issue by RomanBON** [yury-dymov/habr-app#7]
Неправильно указан путь к js и css файлам для продакшн сборки
`<link rel="stylesheet" href="//public/assets/styles.css">`
` <script type="application/javascript" src="//public/assets/bundle.js"></script>`

**Comment by yury-dymov** [comment]
Вполе правильно. В production не express отдает assets, а nginx. Как я его [nginx] настроил — оттуда он и отдаст.

**Comment by RomanBON** [comment]
@yury-dymov Скажите пожалуйста, а как настроить чтобы можно было запустить через express?

**Comment by yury-dymov** [comment]
1) поправить пути для сборки или положить файлы в соответствующие директории
2) для DEV там express уже настроен отдавать статику (server.js)

Но лучше не стрелять себе в ногу, и отдавать nginx'ом
