### ISSUE TITLE
не правильно используется bluebird глобально webpack.conf.js

### ISSUE THREAD

**Issue by mymtw** [yury-dymov/habr-app#8]
У вас скорее всего не правильно используется `bluebird`. (А вернее вообще не используется)
Вы сделали чтобы он был глобальным в проекте и указали в `webpack.conf.js`:
`global.Promise = require('bluebird');`
У меня он так не включается в проект.
Мне помогла такая строчка:
```
  plugins: [
    new webpack.ProvidePlugin({
      Promise: 'bluebird'
    }),
 ];
```
Или это из-за того, что у меня `webpack 3`?

**Comment by yury-dymov** [comment]
Ну, в проекте webpack 1 :)
Думаю, что дело действительно в этом.
Я не поддерживаю этот boilerplate, так как надо слишком много всего обновлять, как в проекте, так и в статьях
