### ISSUE TITLE
Ошибка при обращению к серверу

### ISSUE THREAD

**Issue by martrix78** [yury-dymov/habr-app#9]
Добрый день, на основе вашего приложения начал делать свое, но вот такая проблема - 
я создал layout компонент c таким кодом
`...
 <a href='https://www.facebook.com'>
<img src={require('./assets/img/facebook.png')}  />
</a>
`
все компилируется нормально, но когда я запускаю nodemon то он валится с ошибкой

> Server listening on: 3001
(node:10551) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: /var/www/react.loc/react_frontend/src/layouts/Promo/assets/img/facebook.png: Unexpected character '�' (1:0)
(node:10551) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

как это можно подправить?

**Comment by yury-dymov** [comment]
Сюда добавить https://github.com/yury-dymov/habr-app/blob/master/server.js `.png`
